// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqmwavnqsatgwsdteuav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxbXdhdm5xc2F0Z3dzZHRldWF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNzgzNzAsImV4cCI6MjA1Nzk1NDM3MH0.ZnKIpUlvrf1sWZJYqAekUmfRBdEVvHK1SEaqj3yJ0F8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);